// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rodnix.EvaLuma.Data;

#nullable disable

namespace Rodnix.EvaLuma.Migrations
{
    [DbContext(typeof(EvalumaDbContext))]
    [Migration("20260612144327_AddRamificationAndAES")]
    partial class AddRamificationAndAES
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Rodnix.EvaLuma.Models.AsignacionProgreso", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<decimal>("CalificacionTemporal")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("calificacion_temporal");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaUltimaAccion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ultima_accion");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdSimulacion")
                        .HasColumnType("int")
                        .HasColumnName("id_simulacion");

                    b.Property<string>("UltimoCheckpoint")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ultimo_checkpoint");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdSimulacion");

                    b.ToTable("Asignacion_Progreso");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.BitacoraAuditoria", b =>
                {
                    b.Property<long>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_evento");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("IdEvento"));

                    b.Property<string>("AccionRealizada")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("accion_realizada");

                    b.Property<string>("HashCriptografico")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("hash_criptografico");

                    b.Property<string>("HashPrevio")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("hash_previo");

                    b.Property<int>("IdAsignacion")
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion");

                    b.Property<DateTime>("MarcaTiempo")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("marca_tiempo");

                    b.Property<int>("TiempoRespuestaMs")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_respuesta_ms");

                    b.HasKey("IdEvento");

                    b.HasIndex("HashCriptografico")
                        .IsUnique();

                    b.HasIndex("IdAsignacion");

                    b.ToTable("Bitacora_Auditoria");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Campana", b =>
                {
                    b.Property<int>("IdCampana")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_campana");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCampana"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estricta")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estricta");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime>("FechaLimite")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_limite");

                    b.Property<int>("IdAuditor")
                        .HasColumnType("int")
                        .HasColumnName("id_auditor");

                    b.Property<string>("NombreCampana")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre_campana");

                    b.HasKey("IdCampana");

                    b.HasIndex("IdAuditor");

                    b.ToTable("Campanas");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.OpcionRespuesta", b =>
                {
                    b.Property<int>("IdOpcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOpcion"));

                    b.Property<bool>("EsCorrecta")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdPregunta")
                        .HasColumnType("int");

                    b.Property<int?>("IdSiguientePregunta")
                        .HasColumnType("int");

                    b.Property<string>("TextoOpcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("IdOpcion");

                    b.HasIndex("IdPregunta");

                    b.ToTable("OpcionesRespuesta");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Pregunta", b =>
                {
                    b.Property<int>("IdPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPregunta"));

                    b.Property<int>("IdSimulacion")
                        .HasColumnType("int");

                    b.Property<string>("TextoPregunta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("ValorPuntos")
                        .HasColumnType("int");

                    b.HasKey("IdPregunta");

                    b.HasIndex("IdSimulacion");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Simulacion", b =>
                {
                    b.Property<int>("IdSimulacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_simulacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdSimulacion"));

                    b.Property<int>("IdCampana")
                        .HasColumnType("int")
                        .HasColumnName("id_campana");

                    b.Property<int?>("TiempoEstimadoMinutos")
                        .HasColumnType("int")
                        .HasColumnName("tiempo_estimado_minutos");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("titulo");

                    b.Property<int>("TotalPreguntas")
                        .HasColumnType("int")
                        .HasColumnName("total_preguntas");

                    b.HasKey("IdSimulacion");

                    b.HasIndex("IdCampana");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departamento");

                    b.Property<string>("EmailCorporativo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_corporativo");

                    b.Property<bool>("Estatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rol");

                    b.Property<string>("SsoIdentificador")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sso_identificador");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.AsignacionProgreso", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.Usuario", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rodnix.EvaLuma.Models.Simulacion", "Simulacion")
                        .WithMany()
                        .HasForeignKey("IdSimulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.BitacoraAuditoria", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.AsignacionProgreso", "Asignacion")
                        .WithMany()
                        .HasForeignKey("IdAsignacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignacion");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Campana", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.Usuario", "Auditor")
                        .WithMany()
                        .HasForeignKey("IdAuditor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auditor");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.OpcionRespuesta", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.Pregunta", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("IdPregunta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Pregunta", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.Simulacion", "Simulacion")
                        .WithMany("Preguntas")
                        .HasForeignKey("IdSimulacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulacion");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Simulacion", b =>
                {
                    b.HasOne("Rodnix.EvaLuma.Models.Campana", "Campana")
                        .WithMany()
                        .HasForeignKey("IdCampana")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campana");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Pregunta", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Simulacion", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}
