// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rodnix.EvaLuma.Data;

#nullable disable

namespace Rodnix.EvaLuma.Migrations
{
    [DbContext(typeof(EvalumaDbContext))]
    partial class EvalumaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Rodnix.EvaLuma.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departamento");

                    b.Property<string>("EmailCorporativo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_corporativo");

                    b.Property<bool>("Estatus")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rol");

                    b.Property<string>("SsoIdentificador")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("sso_identificador");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
